# ===================================================================
# EchoEnchants Mod - Custom enchantments from hostile mobs
# ===================================================================
# Mod loader configuration for Minecraft Forge 1.20.1
modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/echoenchants/echoenchants/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/echoenchants/echoenchants"
logoFile = "assets/echo_enchants/logo.png"
credits = "Created for Minecraft 1.20.1 Forge"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

